config/routes.rb
Splurty::Application.routes.draw do

  root 'quotes#index'
  resources :quotes
  get 'about', :to => 'quotes#about'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
	validates :saying, :presence => true, :length => { :maximum => 140, :minimum => 3 }
	validates :author, :presence => true, :length => { :maximum => 50, :minimum =>3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		@quote = Quote.order("RANDOM()").first
	end

	def create
	    @quote = Quote.create(quote_params)
	    if @quote.invalid?
	      flash[:error] = '<strong>Could not save.</strong> The data you entered is invalid.'
	    end
		redirect_to root_path
	end

	def about
	end

	private

	def quote_params
		params.require(:quote).permit(:saying, :author)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Splurty</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<div class="col-xs-2">
		<%= link_to root_path, :class => 'logo' do %>
		<div class="circle">
      <br />
      L
		  <br />
      O
		  <br />
		  L
		  <br />
		</div>
		<% end %>
	</div>
	<div class="col-xs-5 hidden-xs slogan" style="text-align: left">Funny things kids say.</div>

	<div class="col-xs-5 col-xs-offset-1 col-sm-offset-0 col-sm-5 links">
<!-- Button trigger modal -->
<span style="padding-right: 20px"><%= link_to 'Contribute', '#', :data => {:toggle => 'modal', :target => '#myModal'} %></span>
		<%= link_to 'About', about_path %>
	</div>
</header>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Contribute Your Quote</h4>
        </div>
        <%= simple_form_for Quote.new do |f| %>
          <div class="modal-body">
            <%= f.input :saying, :label => "What is the quote you want to add?", :placeholder => "Does Santa take potty breaks?" %>
            <%= f.input :author, :label => "Who is the funny kid (First Name)?", :placeholder => 'Jimmy' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Add Quote', :class => 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<hr />

<br class= "clear" />

<div class="container">
    <% if flash[:error].present? %>
      <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>
<%= yield %>
</div>

<footer class="footer">
  <div class="container">
  	<div class="col-xs-12 col-sm-6">
  		<%= link_to "This isn't enough, I need more", root_path, :class => 'next-quote' %>
  	</div>
  	<div class="col-xs-12 col-sm-6 footer-blurb">
  		This app proves that old dogs can learn new tricks.
  	</div>
  </div>
</footer>

</body>
</html>

app/views/quotes/about.html.erb
<div class="col-xs-10 col-xs-offset-1 about">
  <h1>About This App</h1>
  <p>
This app was built as an exercise in learning how to use Ruby on Rails, HTML, CSS, and the Bootstrap framework. This app is a simple way for anyone to share the laugh out loud moments inspired by the little ones. Share your kids' funny quotes too, <%= link_to 'contribute here', new_quote_path %>.
</p>

<div class="container-fluid" style="padding: 20px 0px">
<div class= "col-xs-4">
	<%= image_tag 'jaisa.jpg', :class => 'img-responsive round' %>
	</div>
<div class= "col-xs-4">
	<%= image_tag 'camden.jpg', :class => 'img-responsive round' %>
</div>
<div class= "col-xs-4">
	<%= image_tag 'rilynn.jpg', :class => 'img-responsive round' %>
</div>
</div>

<p>The content was inspired by Jaisa, Camden and Rilynn and the crazy things they say. Kids make the best comedians. 
</p>
  
<br />
<br />
<br />
</div>

app/views/quotes/index.html.erb
<h2>
	<span>SPLURTY / No. <%= @quote.id %>
	Yet another example of the funny things kids say ... </span>
</h2>

<h1 class= "quote"><%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />